api:
  errors:
    record_not_found: "Requested record not found"
    generic: "There seems to be a problem. Please try again in a little while."
    parameters_error: "Something wrong with data that we get from you. Please try again."
    image_processing_failed: "Something wrong with processing of you photo, please try another"
    device_not_found: "Device with current token not found. Please try enroll again."
